#!/bin/bash
set -x
set -e

REPO=git://git.savannah.gnu.org/emacs.git
BUILD_ID=`date +%Y-%m-%d_%H-%M-%S`
cd `dirname $0`
if [ ! -d emacs-git ]; then
    git clone $REPO emacs-git
fi
NEWREV=`GIT_DIR=emacs-git/.git git log -1 --oneline | cut -d' ' -f1`
DIR=emacs-${BUILD_ID}-${NEWREV}
rm -rf $DIR
mkdir $DIR
cp -rf emacs-git/* $DIR
(cd $DIR && ./autogen.sh)
tar cjf $DIR.tar.bz2 --exclude '.git' $DIR
rm -rf $DIR
./build-emacs-from-tar $DIR.tar.bz2 nightly
rm $DIR.tar.bz2
./combine-and-package Emacs-${BUILD_ID}-${NEWREV}*.tar.bz2
rm Emacs-${BUILD_ID}-${NEWREV}*.tar.bz2
