#!/bin/bash
set -x
set -e

. ./notify
. ./build-emacs-functions

REPO=git://git.savannah.gnu.org/emacs.git
BASE=Emacs-`date +%F`
CHANGES=emacs-builds/$BASE.changes

cd `dirname $0`
if [ ! -d emacs-git ]; then
    git clone $REPO emacs-git
fi
NEWREV=`GIT_DIR=emacs-git/.git git log -1 --oneline | cut -d' ' -f1`
mkdir -p emacs-builds
DIR=emacs-git-${NEWREV}
rm -rf $DIR
mkdir $DIR
cp -rf emacs-git/* $DIR
build_emacs "$DIR" $BASE-$NEWREV
